# Use the official MySQL image from the Docker Hub
FROM mysql:latest

# Set environment variables for MySQL root password
ENV MYSQL_ROOT_PASSWORD=my-secret-pw

# Expose the MySQL port (default is 3306)
EXPOSE 3307