FROM ubuntu:latest

RUN apt update
RUN apt install -y openjdk-17-jdk

WORKDIR /app

COPY api-gateway-hospital-0.0.1-SNAPSHOT.jar /app/api-gateway-hospital-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar","api-gateway-hospital-0.0.1-SNAPSHOT.jar"]