FROM ubuntu:latest

RUN apt update
RUN apt install -y openjdk-17-jdk

WORKDIR /app

COPY case_service-0.0.1-SNAPSHOT.jar /app/case_service-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar","case_service-0.0.1-SNAPSHOT.jar"]